In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("casual-shoes.csv")

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,20129438,Skechers,Men Blue Textured Sneakers,3.8,11,12999.0,30.0,"""₹7,799.00""",INR,http://assets.myntassets.com/assets/images/201...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",LSD███FES███ES █████████IMI██████,"[{""size"":""6"",""value"":""25.0cm"",""value_name"":""To...",NaN,118███GH ███H C█████████OGE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
1,18506050,Bata,Women Black Woven Design Slip-On Sneakers,4.4,86,1199.0,55.0,"""₹539.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":4,""4_stars"":...",NaN,Bat███ndi███imi██████,"[{""size"":""2"",""value"":""22.8cm"",""value_name"":""To...",NaN,BAT███NDI███TDG█████████ Ha███████████████,NaN,"{""applicable_on"":""Orders above Rs. 599 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
2,21739362,Prolific,Men Printed LightWeight Mid Top Sneakers,3.9,8,2660.0,71.0,"""₹771.00""",INR,http://assets.myntassets.com/assets/images/217...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, A Littl...",BRA███SI ███AIL███,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...",NaN,F 1███ Pr███sso█████████Kam███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
3,21903832,U.S. Polo Assn.,Women Perforated Sneakers,4.1,16,4299.0,25.0,"""₹3,224.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""3"",""value"":""24.0cm"",""value_name"":""To...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
4,21651940,HIGHLANDER,Men Black Woven Design Sneakers,3.4,25,1898.0,55.0,"""₹569.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":5,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Loose""...",Fla███tar███mme██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes

In [4]:
df.shape

(23, 24)

In [5]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [6]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [7]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
18,17312144,Clarks,Men Black Perforations Nubuck Derbys,3.7,3,10999.0,35.0,"""₹7,149.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
19,17350218,Delize,Men Black Leather High-Top Flat Boots,0.0,0,13999.0,68.0,"""₹4,479.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Daz███ Ex███ts,"[{""size"":""6"",""value"":""26.7cm"",""value_name"":""To...",NaN,"C-1███SIT███, I█████████ AR███████████████████...",[{}],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
20,17361518,Buckaroo,Men Tan Brown Solid Leather Flat Boots,0.0,0,4999.0,25.0,"""₹3,749.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nag███ Li███tyl███,"[{""size"":""5"",""value"":""24.5cm"",""value_name"":""To...","[""rw-17361518_cae700""]",402███Win███Mee█████████ Dh███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
21,16284648,Crew STREET,Women Sea Green Woven Design Slip-On Sneakers,4.1,41,3099.0,55.0,"""₹1,394.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":2,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""4"",""value"":""23.5cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
22,19103830,PUMA Motorsport,Unisex Black Perforations BMW MMS Neo Cat Regu...,4.5,157,6999.0,55.0,"""₹4,199.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":11,""2_stars"":3,""3_stars"":5,""4_stars""...",NaN,Sup███om ███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              23 non-null     int64
 1   title                   23 non-null     object
 2   product_description     23 non-null     object
 3   rating                  23 non-null     float64
 4   ratings_count           23 non-null     int64
 5   initial_price           23 non-null     float64
 6   discount                22 non-null     float64
 7   final_price             23 non-null     object
 8   currency                23 non-null     object
 9   images                  23 non-null     object
 10  delivery_options        23 non-null     object
 11  product_details         23 non-null     object
 12  breadcrumbs             23 non-null     object
 13  product_specifications  23 non-null     object
 14  amount_of_stars         23 non-null     object
 15  what_customers_said     11 non-null     object
 16  seller_name             20 non-null     object
 17  sizes                   23 non-null     object
 18  videos                  4 non-null      object
 19  seller_information      20 non-null     object
 20  variations              12 non-null     object
 21  best_offer              23 non-null     object
 22  more_offers             23 non-null     object
 23  category                23 non-null     object
dtypes: float64(3), int64(2), object(19)
memory usage: 4.4+ KB

In [9]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   1
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       12
seller_name                3
sizes                      0
videos                    19
seller_information         3
variations                11
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [10]:
df.fillna("Not Available", inplace=True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_27180\3513367982.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Not Available", inplace=True)

In [11]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(23, 24)

In [15]:
df[df["rating"] > 4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,18506050,Bata,Women Black Woven Design Slip-On Sneakers,4.4,86,1199.0,55.0,"""₹539.00""",INR,http://assets.myntassets.com/assets/images/185...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":4,""4_stars"":...",Not Available,Bat███ndi███imi██████,"[{""size"":""2"",""value"":""22.8cm"",""value_name"":""To...",Not Available,BAT███NDI███TDG█████████ Ha███████████████,Not Available,"{""applicable_on"":""Orders above Rs. 599 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
3,21903832,U.S. Polo Assn.,Women Perforated Sneakers,4.1,16,4299.0,25.0,"""₹3,224.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":3,""4_stars"":...",Not Available,ARV███ LI███TYL█████████LIM██████,"[{""size"":""3"",""value"":""24.0cm"",""value_name"":""To...",Not Available,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
5,21321784,San Frissco,Men Colourblocked Sneakers,4.3,6,5995.0,72.0,"""₹1,678.00""",INR,http://assets.myntassets.com/assets/images/213...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",ARY███ FO███EAR█████████PVT██████,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",Not Available,Ary███ fo███ear█████████vt ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
8,21497770,Puma,Men Sneakers,4.1,111,4999.0,55.0,"""₹2,249.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":13,""2_stars"":6,""3_stars"":6,""4_stars""...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",Pum███por███Ind█████████td.█████████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-21497770_cae700""]",Pum███por███Ind█████████d/ ███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
13,18489168,TOMS,Women Red Solid Alpargata Canvas Slip-On Sneakers,4.3,6,4999.0,Not Available,"""₹4,999.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",Not Available,V R███il ███ Lt███,"[{""size"":""3"",""value"":""22.0cm"",""value_name"":""To...",Not Available,"Sil███Sum███, G█████████or,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
16,17312062,Clarks,Men Blue Nubuck Penny Loafers,4.6,31,6999.0,50.0,"""₹6,999.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",CLA███ RE███NCE█████████ PV██████,"[{""size"":""6"",""value"":""24.6cm"",""value_name"":""To...",Not Available,"Kil███o. ███/ 1█████████, 1███████████████████...",Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
21,16284648,Crew STREET,Women Sea Green Woven Design Slip-On Sneakers,4.1,41,3099.0,55.0,"""₹1,394.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":2,""4_stars"":...",Not Available,Sup███om ███,"[{""size"":""4"",""value"":""23.5cm"",""value_name"":""To...",Not Available,Plo███o- ███ 1s█████████Sui███████████████████...,Not Available,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes
22,19103830,PUMA Motorsport,Unisex Black Perforations BMW MMS Neo Cat Regu...,4.5,157,6999.0,55.0,"""₹4,199.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":11,""2_stars"":3,""3_stars"":5,""4_stars""...",Not Available,Sup███om ███,"[{""size"":""3"",""value"":""21.8cm"",""value_name"":""To...",Not Available,Plo███o- ███ 1s█████████Sui███████████████████...,Not Available,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",casual-shoes

In [16]:
df[["title", "rating", "initial_price"]]

                        title  rating  initial_price
0                    Skechers     3.8        12999.0
1                        Bata     4.4         1199.0
2                    Prolific     3.9         2660.0
3             U.S. Polo Assn.     4.1         4299.0
4                  HIGHLANDER     3.4         1898.0
5                 San Frissco     4.3         5995.0
6                  Eego Italy     0.0         2999.0
7                     MOZAFIA     4.0         1999.0
8                        Puma     4.1         4999.0
9       HRX by Hrithik Roshan     3.9         3299.0
10                      WROGN     3.7         3599.0
11                     FAUSTO     3.2          999.0
12                     FAUSTO     2.5         1299.0
13                       TOMS     4.3         4999.0
14  Fame Forever by Lifestyle     0.0          999.0
15                 HIGHLANDER     3.9         2198.0
16                     Clarks     4.6         6999.0
17                     EVERLY     3.7         1499.0
18                     Clarks     3.7        10999.0
19                     Delize     0.0        13999.0
20                   Buckaroo     0.0         4999.0
21                Crew STREET     4.1         3099.0
22            PUMA Motorsport     4.5         6999.0

In [17]:
df["total_amount"] = df["initial_price"] * df["ratings_count"]

In [18]:
df[["title","initial_price","ratings_count","total_amount"]].head()

             title  initial_price  ratings_count  total_amount
0         Skechers        12999.0             11      142989.0
1             Bata         1199.0             86      103114.0
2         Prolific         2660.0              8       21280.0
3  U.S. Polo Assn.         4299.0             16       68784.0
4       HIGHLANDER         1898.0             25       47450.0

In [19]:
df.to_csv("cleaned_casual_shoes.csv", index=False)